services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: streamvod
      MYSQL_USER: mydb
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: rootpass
    ports: ["3306:3306"]
    command: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--bind-address=0.0.0.0"]
    volumes:
      - dbdata:/var/lib/mysql
      - ../sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ../sql/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
volumes: { dbdata: {} }
